blank_issues_enabled: true
contact_links:
  - name: ADD
    about: Issue template
    url: https://github.com/sintaro-katuta/pulse/issues/new?template=issue_add_template.md&labels=ğŸ’«æ–°æ©Ÿèƒ½
  
  - name: BUG
    about: Issue template
    url: https://github.com/sintaro-katuta/pulse/issues/new?template=issue_bug_template.md&labels=â›”ãƒã‚°å ±å‘Š
